/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlogCategory = { 'clinicalObservation' : null } |
  { 'interview' : null } |
  { 'personalStory' : null };
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'publishedDate' : Time,
  'featuredImageUrl' : [] | [string],
  'category' : BlogCategory,
}
export interface BlogStats {
  'lastUpdated' : Time,
  'totalPortfolioItems' : bigint,
  'totalPosts' : bigint,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'imageUrls' : Array<string>,
  'description' : string,
  'location' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, BlogCategory, [] | [string]],
    bigint
  >,
  'createPortfolioItem' : ActorMethod<
    [string, string, Array<string>, string],
    bigint
  >,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPostsByCategory' : ActorMethod<[BlogCategory], Array<BlogPost>>,
  'getBlogStats' : ActorMethod<[], BlogStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioItem' : ActorMethod<[bigint], [] | [PortfolioItem]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, BlogCategory, [] | [string]],
    undefined
  >,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, Array<string>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];