/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogCategory = IDL.Variant({
  'clinicalObservation' : IDL.Null,
  'interview' : IDL.Null,
  'personalStory' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'publishedDate' : Time,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'category' : BlogCategory,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const BlogStats = IDL.Record({
  'lastUpdated' : Time,
  'totalPortfolioItems' : IDL.Nat,
  'totalPosts' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, BlogCategory, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [BlogCategory],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getBlogStats' : IDL.Func([], [BlogStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolioItem' : IDL.Func([IDL.Nat], [IDL.Opt(PortfolioItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, BlogCategory, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updatePortfolioItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogCategory = IDL.Variant({
    'clinicalObservation' : IDL.Null,
    'interview' : IDL.Null,
    'personalStory' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'publishedDate' : Time,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'category' : BlogCategory,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const BlogStats = IDL.Record({
    'lastUpdated' : Time,
    'totalPortfolioItems' : IDL.Nat,
    'totalPosts' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, BlogCategory, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostsByCategory' : IDL.Func(
        [BlogCategory],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getBlogStats' : IDL.Func([], [BlogStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolioItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PortfolioItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, BlogCategory, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updatePortfolioItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };